//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowRecord
    {
        public int Id { get; set; }
        public System.Guid UserAggregateRootId { get; set; }
        public System.Guid BookAggregateRootId { get; set; }
        public bool Returned { get; set; }
        public Nullable<System.DateTime> BorrowedDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
    }
}
