//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public System.Guid AggregateRootId { get; set; }
        public string AggregateRootType { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Version { get; set; }
        public string EventType { get; set; }
        public string Data { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public bool Synchronized { get; set; }
    }
}
